# Makefile.Host
TOP = ../../..
include $(TOP)/config/CONFIG_APP
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

DBDINSTALL += devAoDAC128V.dbd

# ip330PID.cc -> Ip330PID.h -> DAC128V.h
# Hence, one of ip330's build dependencies is the DAC128V.h file.
INC += DAC128V.h

include $(TOP)/config/RULES.Host
#----------------------------------------
#  ADD RULES AFTER THIS LINE
